first commit
adikarthik/React-B4-1 pull request #11
Opened 2024-05-18 11:21 UTC by vinodkumarc04

Services and portfolio

2024-05-19 13:49 UTC, ashok2world approved these changes

2024-05-20 14:40 UTC, pooventhirankp27 requested changes

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/components copy/Cards.jsx
> +      <div className="card">
Is this css required? don't see any import statement

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/components copy/Cards.jsx
> +const Cards = ({ title, iconPath, description, iconColor }) => {
import react first always

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/components copy/CardsContainer.jsx
> +import Cards from "./Cards";
don't give folder name with white space

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/components copy/CardsContainer.jsx
> +import Cards from "./Cards";
import react

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/components copy/CardsContainer.jsx
> +      {cardData.map((card, i) => (
instead of i, keep it as key

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/components copy/ImageContainer.jsx
> +import { imagesData } from "../utils/Constants";
always import react. do this changes wherever applicable

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/components copy/Portfolio.jsx
> +      <h4 className="portfolio">PORTFOLIO</h4>
Is this css required? don't see any import. import react first

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/components copy/Service.jsx
> +      <h4 className="services">Services</h4>
Is this css required?

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/utils/Constants.jsx
> +export const cardData = [
keep this as .js file.

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/utils/Constants.jsx
> +export const imagesData = [
give more specific name. example, if portfolio images, it should be portfolioImages

2024-05-20 14:40 UTC, pooventhirankp27 commented on src/index.css
>  body {
don't use index.css file. inside your components create separate file and put the css code

2024-05-20 14:41 UTC, pooventhirankp27 requested changes

2024-05-20 14:41 UTC, pooventhirankp27 commented on src/components copy/CardsContainer.jsx
> +import Cards from "./Cards";
Add the logic inside components folder.

2024-05-23 09:04 UTC, pooventhirankp27 requested changes

2024-05-23 09:04 UTC, pooventhirankp27 commented on src/index.css
>  body {
don't commit index.css file

2024-05-23 09:04 UTC, pooventhirankp27 commented on src/utils/Constants.js
> +export const ServiceCardData = [
keep it in camel case

2024-05-23 09:04 UTC, pooventhirankp27 commented on src/App.js
don't commit app.js file

2024-05-23 09:04 UTC, pooventhirankp27 commented on src/components copy/ImageCard.jsx
if this folder is not required, remove it.

2024-05-23 10:14 UTC, vinodkumarc04 commented on src/components copy/ImageCard.jsx
it's not required in components copy folder so removed in my project

2024-05-23 14:48 UTC, pooventhirankp27 approved these changes

2024-05-23 14:48 UTC, merged

2024-05-23 14:49 UTC, pooventhirankp27 commented
Delete components copy folder in next PR