change the code
adikarthik/React-B4-1 pull request #8
Opened 2024-05-17 14:38 UTC by venkateshk77

2024-05-17 15:08 UTC, pooventhirankp27 requested changes

2024-05-17 15:08 UTC, pooventhirankp27 commented on src/components/About.css
> +    content: "";
why empty string in css file?

2024-05-20 06:28 UTC, venkateshk77 commented on src/components/About.css
> +    content: "";
If i removed the empty string and horizontal line after the word "about," it will not be visible in the user interface.

2024-05-20 14:46 UTC, pooventhirankp27 requested changes

2024-05-20 14:46 UTC, pooventhirankp27 commented on src/components/About.css
create folder inside components and add your files. should not add jsx file inside components.

2024-05-22 14:13 UTC, pooventhirankp27 requested changes

2024-05-22 14:13 UTC, pooventhirankp27 commented on src/components/About/About.css
> +<<<<<<< HEAD:src/components/About/About.css
resolve conflicts properly

2024-05-22 14:13 UTC, pooventhirankp27 commented on src/components/About/About.css
> +<<<<<<< HEAD:src/components/About/About.css
resolve conflicts properly

2024-05-22 14:13 UTC, pooventhirankp27 commented on src/components/Team.css
> +}
add new line at the end of file

2024-05-22 14:13 UTC, pooventhirankp27 commented on src/components/Card/Cards.css
> +}
add new file at the end of file

2024-05-22 14:13 UTC, pooventhirankp27 commented on src/App.js
> +      <About />
put it in routing

2024-05-22 14:13 UTC, pooventhirankp27 commented on src/components/Team.jsx
create teams folder and add it

2024-05-22 14:13 UTC, pooventhirankp27 commented on src/components/Team.jsx
create teams folder and add it

2024-05-22 14:13 UTC, pooventhirankp27 commented on src/components/Team.css
create teams folder and add it

2024-05-22 15:25 UTC, pooventhirankp27 requested changes

2024-05-22 15:25 UTC, pooventhirankp27 commented on src/components/Team.css
if it's duplicate, don't commit

2024-05-22 15:25 UTC, pooventhirankp27 commented on src/components/Team.jsx
if it's duplicate, don't commit

2024-05-23 08:58 UTC, pooventhirankp27 approved these changes

2024-05-23 08:58 UTC, merged